#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8002
#mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  #type-aliases-package: com.yq.spider.entity
  #mapper-locations: classpath:mybatis/mapper/**/*.xml
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yq.spider.entity
  mapper-locations: classpath:/mybatis/mapper/*.xml
spring:
  profiles: dev # 开发环境
  application:
    name: spider-cms			# ******服务名*******
  #datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/spider_cms_dev_8002?serverTimezone=GMT%2B8 # 数据库连接地址，*****注意库名 db01***************
    #username: root
    #password: yqkj2018
    #dbcp2:
      #min-idle: 5
      #initial-size: 5
      #max-total: 5
      #max-wait-millis: 150
    #动态测试多个数据源，可以实现读写分离
    #datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/spider_cms_dev_8002?serverTimezone=GMT%2B8
          username: root
          password: yqkj2018
          driver-class-name: com.mysql.jdbc.Driver
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/spider_cms_dev_8003?serverTimezone=GMT%2B8
          username: root
          password: yqkj2018
          driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  #  暴露触发消息总线的地址
management:
    endpoints:
      web:
        exposure:
          include: "*"
---
server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yq.spider.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: prod # 生产环境
  application:
    name: spider-cms		# ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spider_cms_prod_8002?serverTimezone=GMT%2B8 #数据库连接地址，*****注意库名 db02***************
    username: root
    password: yqkj2018
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
# 在被监控服务上添加暴露端点
management:
    endpoints:
      web:
        exposure:
          include: "*"
