#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
#服务器配置
server:
  #端口
  port: 6004
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yq.spider.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone:  http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
#spring配置
spring:
  #应用配置
  profiles: dev # 开发环境
  application:
    #名称: OAuth2认证授权服务
    name: spider-safe
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/spider_cms_dev_8002?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: yqkj2018
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
#安全配置
security:
  #oauth2配置
  oauth2:
    resource:
      filter-order: 3
---
#服务器配置
server:
  #端口
  port: 6004
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yq.spider.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone:  http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
#spring配置
spring:
  #应用配置
  profiles: prod # 开发环境
  application:
    #名称: OAuth2认证授权服务
    name: spider-safe
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/spider_cms_dev_8002?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: yqkj2018
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
#安全配置
security:
  #oauth2配置
  oauth2:
    resource:
      filter-order: 3
